### ISSUE TITLE
Your models aren't available

### ISSUE THREAD

**Issue by splatboydev** [TheNishishiro/ColorGAN#3]
(Sorry for necropost)

The Google Drive link just comes up with a 404 error when clicked.
It would be helpful for setup if we could have access to them again.

**Comment by TheNishishiro** [comment]
Well, I sure am late, I just notice that the link is no longer working, I tried to search for the model on my google drive but can't seem to find it, I would probably need to look through my old hard drives since I might have accidentaly deleted them while cleaning up.

I will try to get a hold of them again, if I can

**Comment by TheNishishiro** [comment]
Don't seem to have the model anymore, I intend on retraining the whole thing soon anyways

**Comment by splatboydev** [comment]
Alright, thanks

**Comment by splatboydev** [comment]
Glad to see that you're picking this up again
